@apiUrl = http://localhost:3000

### Get all jobs
GET {{apiUrl}}/api/jobs HTTP/1.1

### Create jobs
# @name createJob
POST {{apiUrl}}/api/jobs HTTP/1.1
Content-Type: application/json

{
    "position": "dev",
    "company": "Facebook",
    "jobLocation": "ONSITE",
    "jobType": "FULL_TIME",
    "jobStatus": "PENDING",
    "userId": "ec1f45ec-664e-45ea-a8bd-a01a2d1acf8d"
}

###

@jobId = {{createJob.response.body.id}}

### Get jobs by id
GET {{apiUrl}}/api/jobs/{{ jobId }} HTTP/1.1

### Update jobs by id
PUT {{apiUrl}}/api/jobs/{{ jobId }} HTTP/1.1
Content-Type: application/json

{
    "position": "EDITED dev",
    "company": "Google",
    "jobLocation": "ONSITE",
    "jobType": "FULL_TIME",
    "jobStatus": "INTERVIEW"
}

### Delete job by id
DELETE {{apiUrl}}/api/jobs/{{ jobId }} HTTP/1.1